#!/usr/bin/env node

var fs = require('fs')
var request = require('request')

var options = {
  url: 'https://api.github.com/repos/luckytianyiyan/tylauncher/releases',
  json: true,
  headers: {
    'user-agent': 'TyLauncher'
  }
}
request(options, function (error, response, body) {
  if (error) return console.log(error)
  if (response.statusCode == 200) {
    // remove unused objects
    body.forEach(function (release) {
      delete release.assets
      delete release.author
    })
    fs.writeFileSync('_data/releases.json', JSON.stringify(body, null, 2))
  }
})
